debug: true
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  miniapp:
    appid: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.225.114.20/automan
    username: dev
    password: dev@)#)
mybatis:
  type-aliases-package: com.github.binarywang.demo.wechat.bean
