debug: true
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  miniapp:
    appid: wx84cc48c8ddcf5e08
    secret: 3d2697cd7118d4278c71759a3d992c34
    token: 3e4657cr7146d427t37275da3s093f34
    aesKey: 9k81hwmQQQ0B9HNLbrpPWiDM5AewSBdVHnpGxWUOlH5
    msgDataFormat: JSON
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.225.114.20/automan
    username: dev
    password: dev@)#)
mybatis:
  type-aliases-package: com.github.binarywang.demo.wechat.bean
  configuration:
    map-underscore-to-camel-case: true
